KTB-04
i1qxa/KotlinTelegramBot pull request #3
Opened 2024-10-04 19:48 UTC by i1qxa

Создал меню для тренажера

2024-10-05 10:22 UTC, kaznikit requested changes

2024-10-05 10:22 UTC, kaznikit commented on src/main/kotlin/Main.kt
> +//    println(dictionary.joinToString(separator = "\n"))
Не стоит оставлять закомменттрованный код, если на это нет веских причин или комментария о том, для чего этот код нужен

2024-10-05 10:22 UTC, kaznikit commented on src/main/kotlin/Main.kt
> +            0
Давай выводить ошибку в случае неуспешного парсинга файла, иначе для юзера будет не очевидно что есть какая то проблема

2024-10-05 13:00 UTC, kaznikit requested changes

2024-10-05 13:00 UTC, kaznikit commented on src/main/kotlin/Main.kt
> +            0
я оставлял коммент про показ ошибки юзеру, что сейчас изменилось?

2024-10-05 13:04 UTC, i1qxa commented on src/main/kotlin/Main.kt
> +            0
Я добавил отображение ошибки в блоке ниже, где идет попытка добавить word в список. В этом блоке по умолчанию(если в файле нет данных присваивается значение 0)

2024-10-06 09:27 UTC, kaznikit commented on src/main/kotlin/Main.kt
> +            0
это я понял) говорил про то, что в случае ошибки записывать 0 некорректно. лучше правильно обработать ошибку, показать ее юзеру и не добавлять такое слово в список. сейчас аппрув, но в след ПРе попробуй это исправить

2024-10-06 09:27 UTC, kaznikit approved these changes

2024-10-06 18:01 UTC, merged