KTB-07
i1qxa/KotlinTelegramBot pull request #5
Opened 2024-10-06 19:00 UTC by i1qxa

Реализовал функционал изучения новых слов

2024-10-07 11:44 UTC, kaznikit requested changes

2024-10-07 11:44 UTC, kaznikit commented on src/main/kotlin/Main.kt
> +                println("Вы выбрали: ${listOfVariant[answer!! - 1]}")
в таком случае если юзер введет отличный от числа символ программа упадет. давай обрабатывать такую ситуацию более корректно.

2024-10-07 11:44 UTC, kaznikit commented on src/main/kotlin/Main.kt
> +        val listOfVariant =
мы должны брать варианты ответа из списка невыученных слов. в случае когда у нас в списке невыученных меньше 3 вариантов, тогда мы должны добирать слова для вариантов из уже выученных. то есть здесь будет 2 варианта составления списка

2024-10-07 18:40 UTC, i1qxa commented on src/main/kotlin/Main.kt
> +                println("Вы выбрали: ${listOfVariant[answer!! - 1]}")
так блок else отрабатывает если введено число отличное от 0,1,2,3,4. Или как-то иначе нужно обработать эту ситуацию?

2024-10-08 07:05 UTC, kaznikit commented on src/main/kotlin/Main.kt
> +                println("Вы выбрали: ${listOfVariant[answer!! - 1]}")
да, все так

2024-10-08 07:06 UTC, kaznikit approved these changes

2024-10-08 17:52 UTC, merged